#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

spawn $env(EXAMPLES_DIR)echo

expect -exact "Shout into this cave and hear the echo!\r\n"

send -- "a\r"
expect "  a\r\n"

send -- "123\r"
expect "      123  12 1\r\n" 

send -- "12 ab\r"
expect "          12 ab    12 a   12   12 1\r\n" {
    exit 0
}

puts stderr "\nError: output was different from expected value."
exit 1