#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn $env(EXAMPLES_DIR)file-read-buffered

expect "Done reading file: {bytes_read: 1915, lines_read: 17}\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nExpect script failed: output was different from expected value. uncomment `exp_internal 1` to debug."
exit 1
