#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn $env(EXAMPLES_DIR)file-read-memory-map

expect "First line of LICENSE: Copyright © 2022 Richard Feldman and subsequent basic-cli authors <github.com/roc-lang/basic-cli/graphs/contributors>\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1
