#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn $env(EXAMPLES_DIR)file-test

expect "Pass: expected NotFound\r\nPass: expected PermissionDenied\r\nPass: expected NotFound\r\nPass: expected PermissionDenied\r\nTests complete\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1