#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn ./examples/form


expect "What's your first name?\r\n"

send -- "John\r"

expect "What's your last name?\r\n"

send -- "Doe\r"

expect "Hi, John Doe! 👋\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1