#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

cd $env(EXAMPLES_DIR)
spawn ./path

expect "is_file: Bool.true\r\nis_dir: Bool.false\r\nis_sym_link: Bool.false\r\ntype: IsFile\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nExpect script failed: output was different from expected value. uncomment `exp_internal 1` to debug."
exit 1
