#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

cd $env(EXAMPLES_DIR)
spawn ./path

expect "isFile: (Ok Bool.true) isDir: (Ok Bool.false) isSymLink: (Ok Bool.false) type: (Ok IsFile)\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1
