#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn $env(EXAMPLES_DIR)random

set expected_output [normalize_output "
Random U64 seed is: \\\d+
Random U32 seed is: \\\d+
"]

expect -re $expected_output {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nExpect script failed: output was different from expected value. uncomment `exp_internal 1` to debug."
exit 1