#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn spawn $env(EXAMPLES_DIR)record-builder

expect "Apples: Granny Smith, Pink Lady, Golden Delicious\r\nOranges: Navel, Blood Orange, Clementine\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nError: output was different from expected value."
exit 1