#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn $env(EXAMPLES_DIR)stdin-basic


expect "What's your first name?\r\n"

send -- "John\r"

expect "What's your last name?\r\n"

send -- "Doe\r"

expect "Hi, John Doe! 👋\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nExpect script failed: output was different from expected value. uncomment `exp_internal 1` to debug."
exit 1