#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

# -n to make sure Stdin.read_to_end! works without newline in input

spawn bash -c "echo -n \"hey\" | $env(EXAMPLES_DIR)/stdin-pipe"

expect "This is what you piped in: \"hey\"\r\n" {
    expect eof {
        check_exit_and_segfault
    }
}

puts stderr "\nExpect script failed: output was different from expected value. uncomment `exp_internal 1` to debug."
exit 1