#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

# get path to cat command
set cat_path [exec which cat]
# Start echo server
spawn ncat -e $cat_path -l 8085
sleep 5

spawn $env(EXAMPLES_DIR)tcp-client


expect "Connected!\r\n" {
    expect "> " {
        send -- "Hi\r"
        expect "< Hi\r\n" {
            exit 0            
        }
    }
}

puts stderr "\nExpect failed: output was different from expected value."
exit 1
