#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

# get path to cat command
set cat_path [exec which cat]
# Start echo server
spawn ncat -e $cat_path -l 8085

spawn ./roc_nightly/roc run ./examples/tcp-client.roc --prebuilt-platform=true


expect "Connected!\r\n" {
    expect "> " {
        send -- "Hi\r"
        expect "< Hi\r\n" {
            exit 0            
        }
    }
}


exit 1